# Generated by Django 4.0.5 on 2022-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
